export type FieldType =
  | "text"
  | "number"
  | "date"
  | "datetime"
  | "textarea"
  | "select"
  | "ref"
  | "boolean";

export type Field = {
  key: string;
  label?: string;
  type?: FieldType;
  options?: string[];
  refTable?: RefTable;
  readOnly?: boolean;
};

export type RefTable =
  | "customers"
  | "vehicles"
  | "drivers"
  | "trips"
  | "loads"
  | "tires"
  | "work_orders"
  | "technicians"
  | "contracts";

export type ModuleConfig = {
  table: string;
  title: string;
  subtitle: string;
  prefix?: string;
  prefixKey?: string;
  columns: string[];
  fields: Field[];
  statusKey?: string;
  statusOptions?: string[];
  searchKeys: string[];
};

export const REF_LABEL: Record<RefTable, string> = {
  customers: "name",
  vehicles: "registration_number",
  drivers: "full_name",
  trips: "trip_number",
  loads: "load_reference",
  tires: "serial_number",
  work_orders: "work_order_number",
  technicians: "full_name",
  contracts: "route",
};

export const modules = {
  customers: {
    table: "customers",
    title: "Customers",
    subtitle: "Companies that book loads and receive invoices",
    columns: ["name", "contact_person", "phone", "email", "tax_id", "status"],
    statusKey: "status",
    searchKeys: ["name", "contact_person", "phone", "email"],
    fields: [
      { key: "name" },
      { key: "contact_person" },
      { key: "phone" },
      { key: "email" },
      { key: "address" },
      { key: "tax_id" },
      { key: "status", type: "select", options: ["Active", "On Hold", "Inactive"] },
      { key: "notes", type: "textarea" },
    ],
  },
  vehicles: {
    table: "vehicles",
    title: "Vehicles",
    subtitle: "Trucks and trailers in the fleet",
    columns: ["registration_number", "vehicle_type", "capacity", "odometer", "yard_zone", "status"],
    statusKey: "status",
    searchKeys: ["registration_number", "vehicle_type", "assigned_driver"],
    fields: [
      { key: "registration_number" },
      { key: "vehicle_type" },
      { key: "is_trailer", label: "Is trailer", type: "boolean" },
      { key: "capacity" },
      { key: "odometer", type: "number" },
      {
        key: "status",
        type: "select",
        options: ["Available", "In Yard", "Loading", "On Trip", "In Maintenance", "On Hold"],
      },
      {
        key: "yard_zone",
        type: "select",
        options: ["", "Main Gate", "Parking", "Loading Bay", "Unloading Bay", "Workshop", "Tire Store", "Exit Gate"],
      },
      { key: "assigned_driver" },
      { key: "documents_expiry", type: "date" },
      { key: "notes", type: "textarea" },
    ],
  },
  drivers: {
    table: "drivers",
    title: "Drivers",
    subtitle: "Licensed drivers and their assignments",
    columns: ["full_name", "driver_code", "phone", "licence_number", "licence_expiry", "status"],
    statusKey: "status",
    searchKeys: ["full_name", "driver_code", "phone", "licence_number"],
    fields: [
      { key: "full_name" },
      { key: "driver_code" },
      { key: "phone" },
      { key: "licence_number" },
      { key: "licence_expiry", type: "date" },
      { key: "assigned_vehicle" },
      { key: "monthly_salary_tzs", label: "Monthly salary (TZS)", type: "number" },
      { key: "base_location" },
      { key: "status", type: "select", options: ["Available", "On Trip", "Suspended", "Off Duty"] },
      { key: "notes", type: "textarea" },
    ],
  },
  trips: {
    table: "trips",
    title: "Trips",
    subtitle: "Border journeys, contracts and settlement",
    prefix: "TRP",
    prefixKey: "trip_number",
    columns: ["trip_number", "customer_id", "origin", "destination", "planned_departure", "vehicle_id", "driver_id", "status"],
    statusKey: "status",
    searchKeys: ["trip_number", "origin", "destination"],
    fields: [
      { key: "trip_number", readOnly: true },
      { key: "customer_id", label: "Customer", type: "ref", refTable: "customers" },
      { key: "origin" },
      { key: "destination" },
      { key: "planned_departure", type: "datetime" },
      { key: "planned_arrival", type: "datetime" },
      { key: "vehicle_id", label: "Vehicle", type: "ref", refTable: "vehicles" },
      { key: "trailer_id", label: "Trailer", type: "ref", refTable: "vehicles" },
      { key: "driver_id", label: "Driver", type: "ref", refTable: "drivers" },
      {
        key: "status",
        type: "select",
        options: ["Draft", "Approved", "Ready for Yard", "In Yard", "Dispatched", "In Transit", "At Border", "Delivered", "Pending Settlement", "Completed", "Closed", "Cancelled"],
      },
      { key: "planned_distance", type: "number" },
      { key: "notes", type: "textarea" },
    ],
  },
  loads: {
    table: "loads",
    title: "Loads",
    subtitle: "Cargo planned by the office and verified in the yard",
    prefix: "LD",
    prefixKey: "load_reference",
    columns: ["load_reference", "customer_id", "trip_id", "cargo_description", "expected_quantity", "actual_quantity", "seal_number", "status"],
    statusKey: "status",
    searchKeys: ["load_reference", "cargo_description", "seal_number"],
    fields: [
      { key: "load_reference", readOnly: true },
      { key: "customer_id", label: "Customer", type: "ref", refTable: "customers" },
      { key: "trip_id", label: "Trip", type: "ref", refTable: "trips" },
      { key: "cargo_description" },
      { key: "cargo_category" },
      { key: "expected_quantity", type: "number" },
      { key: "unit_of_measure" },
      { key: "expected_weight", type: "number" },
      { key: "origin" },
      { key: "destination" },
      { key: "planned_loading_date", type: "date" },
      { key: "seal_number" },
      {
        key: "status",
        type: "select",
        options: ["Draft", "Approved", "Awaiting Loading", "Loading", "Loaded", "Verified", "Dispatched", "Delivered", "Reconciled"],
      },
      { key: "notes", type: "textarea" },
    ],
  },
  fuel_allocations: {
    table: "fuel_allocations",
    title: "Fuel Management",
    subtitle: "Fuel budget and allocation per trip — office only",
    prefix: "FA",
    prefixKey: "reference",
    columns: ["reference", "trip_id", "vehicle_id", "fuel_type", "approved_litres", "fuel_cost", "supplier", "status"],
    statusKey: "status",
    searchKeys: ["reference", "supplier", "receipt_number"],
    fields: [
      { key: "reference", readOnly: true },
      { key: "trip_id", label: "Trip", type: "ref", refTable: "trips" },
      { key: "vehicle_id", label: "Vehicle", type: "ref", refTable: "vehicles" },
      { key: "driver_id", label: "Driver", type: "ref", refTable: "drivers" },
      { key: "fuel_type", type: "select", options: ["Diesel", "Petrol"] },
      { key: "planned_litres", type: "number" },
      { key: "approved_litres", type: "number" },
      { key: "fuel_cost", type: "number" },
      { key: "currency" },
      { key: "supplier" },
      { key: "receipt_number" },
      { key: "status", type: "select", options: ["Draft", "Approved", "Reconciled"] },
      { key: "notes", type: "textarea" },
    ],
  },
  work_orders: {
    table: "work_orders",
    title: "Work Orders",
    subtitle: "Workshop jobs and maintenance holds",
    prefix: "WO",
    prefixKey: "work_order_number",
    columns: ["work_order_number", "vehicle_id", "reported_defect", "priority", "technician", "actual_cost", "status"],
    statusKey: "status",
    searchKeys: ["work_order_number", "reported_defect", "technician"],
    fields: [
      { key: "work_order_number", readOnly: true },
      { key: "vehicle_id", label: "Vehicle", type: "ref", refTable: "vehicles" },
      { key: "reported_defect", type: "textarea" },
      { key: "priority", type: "select", options: ["Low", "Medium", "High", "Critical"] },
      { key: "technician" },
      { key: "planned_work", type: "textarea" },
      { key: "status", type: "select", options: ["Open", "In Progress", "Awaiting Inspection", "Completed", "Released"] },
      { key: "odometer", type: "number" },
      { key: "cost_estimate", type: "number" },
      { key: "actual_cost", type: "number" },
      { key: "notes", type: "textarea" },
    ],
  },
  technicians: {
    table: "technicians",
    title: "Technicians",
    subtitle: "Workshop staff",
    columns: ["full_name", "phone", "email", "speciality", "status"],
    statusKey: "status",
    searchKeys: ["full_name", "speciality", "email", "phone"],
    fields: [
      { key: "full_name" },
      { key: "phone" },
      { key: "email" },
      { key: "address" },
      { key: "speciality" },
      { key: "status", type: "select", options: ["Active", "Inactive"] },
    ],
  },
  expenses: {
    table: "expenses",
    title: "Expenses",
    subtitle: "One expense book with categories and links",
    prefix: "EXP",
    prefixKey: "expense_number",
    columns: ["expense_number", "expense_date", "category", "amount", "supplier", "trip_id", "vehicle_id", "status"],
    statusKey: "status",
    searchKeys: ["expense_number", "supplier", "category"],
    fields: [
      { key: "expense_number", readOnly: true },
      { key: "expense_date", type: "date" },
      {
        key: "category",
        type: "select",
        options: [
          "Fuel",
          "Road Tolls",
          "Driver Mileage",
          "Container Drop-off",
          "Miscellaneous",
          "Trip",
          "Maintenance",
          "Yard",
          "Administrative",
          "Emergency",
          "Other",
        ],
      },
      { key: "amount", type: "number" },
      { key: "volume_liters", label: "Volume (litres)", type: "number" },
      { key: "currency" },
      { key: "supplier" },
      { key: "trip_id", label: "Trip", type: "ref", refTable: "trips" },
      { key: "vehicle_id", label: "Vehicle", type: "ref", refTable: "vehicles" },
      { key: "load_id", label: "Load", type: "ref", refTable: "loads" },
      { key: "work_order_id", label: "Work order", type: "ref", refTable: "work_orders" },
      { key: "receipt_url", label: "Receipt link" },
      { key: "status", type: "select", options: ["Draft", "Submitted", "Approved", "Paid", "Rejected"] },
      { key: "notes", type: "textarea" },
    ],
  },
  invoices: {
    table: "invoices",
    title: "Invoices",
    subtitle: "Customer billing",
    prefix: "INV",
    prefixKey: "invoice_number",
    columns: ["invoice_number", "customer_id", "trip_id", "amount", "tax", "due_date", "status"],
    statusKey: "status",
    searchKeys: ["invoice_number"],
    fields: [
      { key: "invoice_number", readOnly: true },
      { key: "customer_id", label: "Customer", type: "ref", refTable: "customers" },
      { key: "trip_id", label: "Trip", type: "ref", refTable: "trips" },
      { key: "load_id", label: "Load", type: "ref", refTable: "loads" },
      { key: "amount", type: "number" },
      { key: "tax", type: "number" },
      { key: "currency" },
      { key: "due_date", type: "date" },
      { key: "status", type: "select", options: ["Draft", "Sent", "Partially Paid", "Paid", "Overdue"] },
      { key: "attachment_url", label: "Attachment link" },
    ],
  },
  vehicle_inspections: {
    table: "vehicle_inspections",
    title: "Vehicle Inspections",
    subtitle: "Yard-recorded inspection results",
    columns: ["vehicle_id", "trip_id", "inspection_type", "result", "odometer", "inspector", "inspected_at"],
    statusKey: "result",
    searchKeys: ["inspection_type", "inspector", "findings"],
    fields: [
      { key: "vehicle_id", label: "Vehicle", type: "ref", refTable: "vehicles" },
      { key: "trip_id", label: "Trip", type: "ref", refTable: "trips" },
      { key: "inspection_type", type: "select", options: ["Pre-trip", "Post-trip", "Gate", "Workshop"] },
      { key: "result", type: "select", options: ["Pass", "Fail", "Pass with defects"] },
      { key: "odometer", type: "number" },
      { key: "findings", type: "textarea" },
      { key: "inspector" },
      { key: "inspected_at", type: "datetime" },
    ],
  },
  tires: {
    table: "tires",
    title: "Tires & Assets",
    subtitle: "Tire register tracked by serial number",
    columns: ["serial_number", "brand", "size", "pattern", "vehicle_id", "wheel_position", "current_location", "status"],
    statusKey: "status",
    searchKeys: ["serial_number", "brand", "pattern", "wheel_position"],
    fields: [
      { key: "serial_number" },
      { key: "brand" },
      { key: "size" },
      { key: "pattern" },
      {
        key: "status",
        type: "select",
        options: ["In Store", "Installed", "Inspection", "Repair/Retread", "Disposal", "Missing", "Disputed"],
      },
      { key: "current_location" },
      { key: "vehicle_id", label: "Installed vehicle", type: "ref", refTable: "vehicles" },
      { key: "wheel_position" },
      { key: "installation_odometer", type: "number" },
      { key: "condition", type: "select", options: ["New", "Good", "Fair", "Worn", "Damaged"] },
      { key: "notes", type: "textarea" },
    ],
  },
  tire_movements: {
    table: "tire_movements",
    title: "Tire Movements",
    subtitle: "Every install, removal and transfer with a verifier",
    columns: ["tire_id", "movement_type", "vehicle_id", "wheel_position", "odometer", "technician", "verifier", "destination_location", "moved_at"],
    searchKeys: ["movement_type", "technician", "verifier", "reason"],
    fields: [
      { key: "tire_id", label: "Tire", type: "ref", refTable: "tires" },
      {
        key: "movement_type",
        type: "select",
        options: ["Install", "Remove", "Transfer", "Send for repair/retread", "Return to store", "Dispose"],
      },
      { key: "vehicle_id", label: "Vehicle", type: "ref", refTable: "vehicles" },
      { key: "wheel_position" },
      { key: "odometer", type: "number" },
      { key: "reason", type: "textarea" },
      { key: "condition", type: "select", options: ["New", "Good", "Fair", "Worn", "Damaged"] },
      { key: "technician" },
      { key: "verifier", label: "Yard / security verifier" },
      { key: "destination_location" },
      { key: "approved", label: "Approved", type: "boolean" },
    ],
  },
  incidents: {
    table: "incidents",
    title: "Incidents & Cases",
    subtitle: "Security incidents, evidence and investigations",
    prefix: "INC",
    prefixKey: "incident_number",
    columns: ["incident_number", "incident_type", "severity", "occurred_at", "location", "vehicle_id", "investigator", "status"],
    statusKey: "status",
    searchKeys: ["incident_number", "incident_type", "description", "investigator"],
    fields: [
      { key: "incident_number", readOnly: true },
      {
        key: "incident_type",
        type: "select",
        options: [
          "Missing Tire",
          "Fuel Variance",
          "Cargo Shortage",
          "Seal Mismatch",
          "Unauthorized Exit Attempt",
          "Damage",
          "Theft Suspected",
          "Accident",
          "Other",
        ],
      },
      { key: "severity", type: "select", options: ["Low", "Medium", "High", "Critical"] },
      { key: "occurred_at", type: "datetime" },
      { key: "location" },
      { key: "vehicle_id", label: "Vehicle", type: "ref", refTable: "vehicles" },
      { key: "driver_id", label: "Driver", type: "ref", refTable: "drivers" },
      { key: "trip_id", label: "Trip", type: "ref", refTable: "trips" },
      { key: "load_id", label: "Load", type: "ref", refTable: "loads" },
      { key: "tire_id", label: "Tire", type: "ref", refTable: "tires" },
      { key: "description", type: "textarea" },
      { key: "people_involved", type: "textarea" },
      { key: "financial_impact", type: "number" },
      { key: "status", type: "select", options: ["Open", "Under Investigation", "Escalated", "Resolved", "Closed"] },
      { key: "investigator" },
    ],
  },
  police_cases: {
    table: "police_cases",
    title: "Police Cases",
    subtitle: "External case references linked to incidents",
    columns: ["case_number", "police_station", "officer_contact", "reported_on", "case_status"],
    statusKey: "case_status",
    searchKeys: ["case_number", "police_station", "officer_contact"],
    fields: [
      { key: "police_station" },
      { key: "case_number" },
      { key: "officer_contact" },
      { key: "reported_on", type: "date" },
      { key: "follow_up_notes", type: "textarea" },
      { key: "case_status", type: "select", options: ["Open", "Under Investigation", "Closed"] },
    ],
  },
  contracts: {
    table: "contracts",
    title: "Contracts",
    subtitle: "Border freight contracts priced in USD",
    columns: ["route", "customer_id", "contract_currency", "contract_amount", "start_date", "end_date", "status"],
    statusKey: "status",
    searchKeys: ["route", "status"],
    fields: [
      { key: "customer_id", label: "Customer", type: "ref", refTable: "customers" },
      { key: "route" },
      { key: "contract_currency", type: "select", options: ["USD", "TZS"] },
      { key: "contract_amount", type: "number" },
      { key: "start_date", type: "date" },
      { key: "end_date", type: "date" },
      { key: "status", type: "select", options: ["Active", "Expired", "Terminated"] },
      { key: "notes", type: "textarea" },
    ],
  },
  vehicle_maintenance: {
    table: "vehicle_maintenance",
    title: "Maintenance",
    subtitle: "Workshop jobs with cost, technician and payment balance",
    columns: ["maintenance_date", "vehicle_id", "description", "technician_id", "cost_tzs", "paid_amount", "status"],
    statusKey: "status",
    searchKeys: ["description", "status"],
    fields: [
      { key: "vehicle_id", label: "Vehicle", type: "ref", refTable: "vehicles" },
      { key: "maintenance_date", type: "date" },
      { key: "description", type: "textarea" },
      { key: "cost_tzs", label: "Cost (TZS)", type: "number" },
      { key: "duration_hours", type: "number" },
      { key: "status", type: "select", options: ["Planned", "In-Progress", "Completed"] },
      { key: "technician_id", label: "Technician", type: "ref", refTable: "technicians" },
      { key: "paid_amount", label: "Paid amount (TZS)", type: "number" },
    ],
  },
  driver_payments: {
    table: "driver_payments",
    title: "Driver Payments",
    subtitle: "Salary, advance and bonus ledger",
    columns: ["payment_date", "driver_id", "payment_type", "amount_tzs", "period_label", "reference_trip"],
    statusKey: "payment_type",
    searchKeys: ["period_label", "notes", "payment_type"],
    fields: [
      { key: "driver_id", label: "Driver", type: "ref", refTable: "drivers" },
      { key: "payment_type", type: "select", options: ["Salary", "Advance", "Bonus"] },
      { key: "amount_tzs", label: "Amount (TZS)", type: "number" },
      { key: "payment_date", type: "date" },
      { key: "period_label", label: "Period (e.g. Sep 2026)" },
      { key: "reference_trip", label: "Trip", type: "ref", refTable: "trips" },
      { key: "notes", type: "textarea" },
    ],
  },
  operational_expenses: {
    table: "operational_expenses",
    title: "Operational Expenses",
    subtitle: "Non-trip costs such as rent, loans, utilities and insurance",
    columns: ["expense_date", "description", "category", "amount_tzs", "receipt_url"],
    statusKey: "category",
    searchKeys: ["description", "category"],
    fields: [
      { key: "description" },
      {
        key: "category",
        type: "select",
        options: ["Rent", "Loan Repayment", "Stationery", "Utilities", "Insurance", "Other"],
      },
      { key: "amount_tzs", label: "Amount (TZS)", type: "number" },
      { key: "expense_date", type: "date" },
      { key: "receipt_url", label: "Receipt link" },
      { key: "notes", type: "textarea" },
    ],
  },
  yard_zones: {
    table: "yard_zones",
    title: "Yard Zones",
    subtitle: "Configurable areas of the yard",
    columns: ["name", "description", "capacity", "active"],
    searchKeys: ["name", "description"],
    fields: [
      { key: "name" },
      { key: "description" },
      { key: "capacity", type: "number" },
      { key: "active", type: "boolean" },
    ],
  },
} satisfies Record<string, ModuleConfig>;

export type ModuleKey = keyof typeof modules;
