/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGateRouteImport } from './routes/_authenticated/gate'
import { Route as AuthenticatedMaintenanceHandoverRouteImport } from './routes/_authenticated/maintenance-handover'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTechniciansRouteImport } from './routes/_authenticated/technicians'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedVerificationRouteImport } from './routes/_authenticated/verification'
import { Route as AuthenticatedYardRouteImport } from './routes/_authenticated/yard'
import { Route as AuthenticatedZonesRouteImport } from './routes/_authenticated/zones'
import { Route as AuthenticatedDriversIndexRouteImport } from './routes/_authenticated/drivers.index'
import { Route as AuthenticatedDriversDriverIdRouteImport } from './routes/_authenticated/drivers.$driverId'
import { Route as AuthenticatedMSlugRouteImport } from './routes/_authenticated/m.$slug'
import { Route as AuthenticatedVehiclesIndexRouteImport } from './routes/_authenticated/vehicles.index'
import { Route as AuthenticatedVehiclesVehicleIdRouteImport } from './routes/_authenticated/vehicles.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGateRoute = AuthenticatedGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceHandoverRoute =
  AuthenticatedMaintenanceHandoverRouteImport.update({
    id: '/maintenance-handover',
    path: '/maintenance-handover',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTechniciansRoute =
  AuthenticatedTechniciansRouteImport.update({
    id: '/technicians',
    path: '/technicians',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerificationRoute =
  AuthenticatedVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYardRoute = AuthenticatedYardRouteImport.update({
  id: '/yard',
  path: '/yard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZonesRoute = AuthenticatedZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversIndexRoute =
  AuthenticatedDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriversDriverIdRoute =
  AuthenticatedDriversDriverIdRouteImport.update({
    id: '/drivers/$driverId',
    path: '/drivers/$driverId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMSlugRoute = AuthenticatedMSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehiclesIndexRoute =
  AuthenticatedVehiclesIndexRouteImport.update({
    id: '/vehicles/',
    path: '/vehicles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehiclesVehicleIdRoute =
  AuthenticatedVehiclesVehicleIdRouteImport.update({
    id: '/vehicles/$vehicleId',
    path: '/vehicles/$vehicleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gate': typeof AuthenticatedGateRoute
  '/maintenance-handover': typeof AuthenticatedMaintenanceHandoverRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/technicians': typeof AuthenticatedTechniciansRoute
  '/users': typeof AuthenticatedUsersRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/yard': typeof AuthenticatedYardRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/drivers/$driverId': typeof AuthenticatedDriversDriverIdRoute
  '/m/$slug': typeof AuthenticatedMSlugRoute
  '/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/drivers/': typeof AuthenticatedDriversIndexRoute
  '/vehicles/': typeof AuthenticatedVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gate': typeof AuthenticatedGateRoute
  '/maintenance-handover': typeof AuthenticatedMaintenanceHandoverRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/technicians': typeof AuthenticatedTechniciansRoute
  '/users': typeof AuthenticatedUsersRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/yard': typeof AuthenticatedYardRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/drivers/$driverId': typeof AuthenticatedDriversDriverIdRoute
  '/m/$slug': typeof AuthenticatedMSlugRoute
  '/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/vehicles': typeof AuthenticatedVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gate': typeof AuthenticatedGateRoute
  '/_authenticated/maintenance-handover': typeof AuthenticatedMaintenanceHandoverRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/technicians': typeof AuthenticatedTechniciansRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/verification': typeof AuthenticatedVerificationRoute
  '/_authenticated/yard': typeof AuthenticatedYardRoute
  '/_authenticated/zones': typeof AuthenticatedZonesRoute
  '/_authenticated/drivers/$driverId': typeof AuthenticatedDriversDriverIdRoute
  '/_authenticated/m/$slug': typeof AuthenticatedMSlugRoute
  '/_authenticated/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/vehicles/': typeof AuthenticatedVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/approvals'
    | '/dashboard'
    | '/gate'
    | '/maintenance-handover'
    | '/reports'
    | '/settings'
    | '/technicians'
    | '/users'
    | '/verification'
    | '/yard'
    | '/zones'
    | '/drivers/$driverId'
    | '/m/$slug'
    | '/vehicles/$vehicleId'
    | '/drivers/'
    | '/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/approvals'
    | '/dashboard'
    | '/gate'
    | '/maintenance-handover'
    | '/reports'
    | '/settings'
    | '/technicians'
    | '/users'
    | '/verification'
    | '/yard'
    | '/zones'
    | '/drivers/$driverId'
    | '/m/$slug'
    | '/vehicles/$vehicleId'
    | '/drivers'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/_authenticated/gate'
    | '/_authenticated/maintenance-handover'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/technicians'
    | '/_authenticated/users'
    | '/_authenticated/verification'
    | '/_authenticated/yard'
    | '/_authenticated/zones'
    | '/_authenticated/drivers/$driverId'
    | '/_authenticated/m/$slug'
    | '/_authenticated/vehicles/$vehicleId'
    | '/_authenticated/drivers/'
    | '/_authenticated/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gate': {
      id: '/_authenticated/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof AuthenticatedGateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance-handover': {
      id: '/_authenticated/maintenance-handover'
      path: '/maintenance-handover'
      fullPath: '/maintenance-handover'
      preLoaderRoute: typeof AuthenticatedMaintenanceHandoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technicians': {
      id: '/_authenticated/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof AuthenticatedTechniciansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification': {
      id: '/_authenticated/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticatedVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yard': {
      id: '/_authenticated/yard'
      path: '/yard'
      fullPath: '/yard'
      preLoaderRoute: typeof AuthenticatedYardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zones': {
      id: '/_authenticated/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AuthenticatedZonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AuthenticatedDriversIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers/$driverId': {
      id: '/_authenticated/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof AuthenticatedDriversDriverIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/$slug': {
      id: '/_authenticated/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof AuthenticatedMSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles/': {
      id: '/_authenticated/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AuthenticatedVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles/$vehicleId': {
      id: '/_authenticated/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof AuthenticatedVehiclesVehicleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGateRoute: typeof AuthenticatedGateRoute
  AuthenticatedMaintenanceHandoverRoute: typeof AuthenticatedMaintenanceHandoverRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTechniciansRoute: typeof AuthenticatedTechniciansRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVerificationRoute: typeof AuthenticatedVerificationRoute
  AuthenticatedYardRoute: typeof AuthenticatedYardRoute
  AuthenticatedZonesRoute: typeof AuthenticatedZonesRoute
  AuthenticatedDriversDriverIdRoute: typeof AuthenticatedDriversDriverIdRoute
  AuthenticatedMSlugRoute: typeof AuthenticatedMSlugRoute
  AuthenticatedVehiclesVehicleIdRoute: typeof AuthenticatedVehiclesVehicleIdRoute
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
  AuthenticatedVehiclesIndexRoute: typeof AuthenticatedVehiclesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGateRoute: AuthenticatedGateRoute,
  AuthenticatedMaintenanceHandoverRoute: AuthenticatedMaintenanceHandoverRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTechniciansRoute: AuthenticatedTechniciansRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVerificationRoute: AuthenticatedVerificationRoute,
  AuthenticatedYardRoute: AuthenticatedYardRoute,
  AuthenticatedZonesRoute: AuthenticatedZonesRoute,
  AuthenticatedDriversDriverIdRoute: AuthenticatedDriversDriverIdRoute,
  AuthenticatedMSlugRoute: AuthenticatedMSlugRoute,
  AuthenticatedVehiclesVehicleIdRoute: AuthenticatedVehiclesVehicleIdRoute,
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
  AuthenticatedVehiclesIndexRoute: AuthenticatedVehiclesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
